name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up GCC
        uses: actions/setup-gcc@v2
        with:
          gcc-version: '10'

      - name: Compile server
        working-directory: ./src/server
        run: make

      - name: Compile client
        working-directory: ./src/client
        run: make

  release:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Archive executables
        uses: actions/upload-artifact@v2
        with:
          name: executables
          path: |
            ./src/server/server
            ./src/client/client

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.sha }}
          release_name: Release ${{ github.sha }}
          body: |
            Changes in this release:
            - Compiled server and client executables

      - name: Upload release artifacts
        id: upload-release-assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./src/server
          asset_name: server
          asset_content_type: application/octet-stream

      - uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./src/client
          asset_name: client
          asset_content_type: application/octet-stream
