name: Build and Release

on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up GCC
        run: sudo apt-get install gcc

      - name: Compile server
        working-directory: ./src/server
        run: make

      - name: Upload server
        uses: actions/upload-artifact@v2
        with:
          name: server
          path: ./src/server/server

      - name: Compile client
        working-directory: ./src/client
        run: make

      - name: Upload client
        uses: actions/upload-artifact@v2
        with:
          name: client
          path: ./src/client/client

  generate-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Generate Minimal PDF
        uses: rseng/pdf-generator@0.0.4
        with:
          paper_markdown: doc/specification.md
          paper_outfile: doc/specification.pdf
          pdf_type: minimal

      - name: Upload PDF
        uses: actions/upload-artifact@v2
        with:
          name: specification
          path: doc/specification.pdf

  release:
    runs-on: ubuntu-latest

    needs: [build, generate-pdf]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Download server
        uses: actions/download-artifact@v2
        with:
          name: server
          path: ./server

      - name: Download client
        uses: actions/download-artifact@v2
        with:
          name: client
          path: ./client

      - name: Download specification
        uses: actions/download-artifact@v2
        with:
          name: specification
          path: ./doc

      - name: Tag the repository
        id: tag
        run: |
          # See https://docs.github.com/en/get-started/using-git/dealing-with-special-characters-in-branch-and-tag-names
          TAG=v$(date -Iseconds | sed 's/[T:\+]/-/g')
          echo "$TAG"
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          git tag -a $TAG -m "Published version $TAG" ${GITHUB_SHA}
          git push origin $TAG

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./server/server
            ./client/client
            ./doc/specification.pdf
          tag_name: ${{ steps.tag.outputs.tag }}