name: Build and Release

on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up GCC
        run: sudo apt-get install gcc

      - name: Compile server
        working-directory: ./src/server
        run: make

      - name: Upload server
        uses: actions/upload-artifact@v2
        with:
          name: server
          path: ./src/server/server

      - name: Compile client
        working-directory: ./src/client
        run: make

      - name: Upload client
        uses: actions/upload-artifact@v2
        with:
          name: client
          path: ./src/client/client

  release:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Download server
        uses: actions/download-artifact@v2
        with:
          name: server
          path: ./server

      - name: Download client
        uses: actions/download-artifact@v2
        with:
          name: client
          path: ./client

      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            ./server/server
            ./client/client
          tag_name: ${{ github.ref }}
          body: |
            Release ${{ github.ref }}
          draft: false
          prerelease: false